### ISSUE TITLE
We would need a specific page for the Caml Consortium

### ISSUE THREAD

**Issue by gasche** [ocaml/v2.ocaml.org#707] opened 2015-10-01 19:14 UTC
In the Contributing.md document planned for the compiler distribution ( ocaml/ocaml#237 ), I point to a reference webpage on the Caml Consortium (to explain the purpose of the Contributor License Agreement). Currently the only page that seems suited to this job is [on caml.inria.fr](http://caml.inria.fr/consortium/). There is a good text about the consortium on [the ocaml.org support.html page](https://ocaml.org/community/support.html#TheCamlConsortiumatInria), but it is among many other things that are not relevant (and it still points to the caml.inria.fr webpage as a reference).

It would be helpful to have a description of the Caml Consortium on its _own_ page (or at least very clearly separated from the rest of the page) that I could use in the Contributing.md document.

**Comment by agarwal** [comment] 2015-10-01 19:26
Okay, I can move this content to a standalone page.

The structure of the remaining page will be a bit odd, since all the other content will be inline. Maybe I'll also move out the OCaml Labs content to a separate page. That might even make more sense since the title of the page is "Commercial Support". Ideally we'd avoid breaking links, so let me think about this for a few minutes and I'll push something.

**Comment by gasche** [comment] 2015-10-01 19:36
Thanks a lot for taking care of the website, and of course there is no hurry.

**Comment by agarwal** [comment] 2015-10-01 20:23
Just realized this is a duplicate of #110, open since Feb 2013! Sigh...

**Closed as completed by agarwal** 2015-10-01 20:23 UTC

**Comment by agarwal** [comment] 2015-10-01 20:30
Done in 45c83647726705b6dbd7991959ade89110d8ee79.
