### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#876] opened 2017-02-20 21:26 UTC
It seems that there is a problem with the renewal of the certificate.

**Comment by gasche** [comment] 2017-02-22 17:15
I just hit this issue today.

**Comment by jcsrb** [comment] 2017-04-20 13:25
It expired

![image](https://cloud.githubusercontent.com/assets/119011/25232992/eaf97ee4-25e5-11e7-9531-35f71dae646d.png)

**Comment by DAMANgoldberg** [comment] 2017-04-21 04:00
Still happening. I discovered this thread after I posted mine.
https://github.com/mirage/mirage/issues/824

**Comment by agarwal** [comment] 2017-08-26 15:34
I'm closing this issue. I'm not sure what happened between Feb when this issue was opened and Aug when #923 was reported. In any case the latter has been resolved.

**Closed as completed by agarwal** 2017-08-26 15:34 UTC

**Comment by dbuenzli** [comment] 2017-08-26 15:51
@agarwal The problem is that it seems that ocaml.org is using Let's encrypt certificate but without automation in place, this should not be done as these certificate are only valid for 90 days. I suspect we'll have the issue again on the 17th of october.

**Comment by agarwal** [comment] 2017-08-26 16:15
Cc @avsm. Do we need to create a new issue requesting a more permanent fix?

**Comment by Chris00** [comment] 2017-08-26 16:26
On 2017-08-26, Ashish Agarwal wrote:
> 
> Cc @avsm. Do we need to create a new issue requesting a more permanent 
> fix?

Please do.  It happens too often.
