### ISSUE TITLE
Improve user experience on https://www.ocaml.org/learn/description.html

### ISSUE THREAD

**Issue by Ndipbanyan** [ocaml/v2.ocaml.org#1422] opened 2021-04-05 22:23 UTC
# Issue Description
When you navigate to any section in /learn/description, you will notice that when you move to a particular content, it becomes tedious to have to scroll to another content up in the page.

# Suggestion
I suggest that the Contents Table  should be styled to a fixed position so that one can easily navigate to any content section by clicking that section on the content table without having to scroll up or down to move to a particular content. 
I will like to fix this.

**Comment by patricoferris** [comment] 2021-04-06 08:15
Thanks @Ndipbanyan for the suggestion, unfortunately somebody already has a PR open to add exactly this functionality. I'm going to close this issue as duplicate of what https://github.com/ocaml/ocaml.org/pull/1423 is solving :))

**Closed as completed by patricoferris** 2021-04-06 08:15 UTC
