### ISSUE TITLE
http://ocaml.org/community/planet/ is empty

### ISSUE THREAD

**Issue by gildor478** [ocaml/v2.ocaml.org#852] opened 2016-10-22 12:23 UTC
As of 2016-10-22T14:22:00+0200 this page is empty....

Maybe related to recent Dyn outage in the US (fail to fetch too many feeds).

**Comment by shayne-fletcher** [comment] 2016-10-27 15:43
On Sat, Oct 22, 2016 at 8:23 AM, Sylvain Le Gall notifications@github.com
wrote:

> As of 2016-10-22T14:22:00+0200 this page is empty....
> 
> Maybe related to recented Dyn outage in the US (fail to fetch too many
> feeds).

​Yes, last day or two, http://ocaml.org/community/planet/ continues to show
empty for me.

## 

Shayne Fletcher

**Comment by hannesm** [comment] 2016-11-06 23:30
this is still the case, and unfortunately http://planet.ocaml.org is redirecting there.... https://ocaml.org/community/planet/syndication.html or https://ocaml.org/feed.xml would be better redirect targets... would be great if someone with access could fix this!

**Comment by gildor478** [comment] 2016-11-07 07:45
http://planet.ocaml.org/atom.xml and http://planet.ocamlcore.org/atom.xml are already redirecting to  http://ocaml.org/feed.xml 

http://planet.ocaml.org was an HTML page for the feed and the best match is/was http://ocaml.org/community/planet/ which is an HTML page as well. A redirect HTML -> Atom would be strange.

**Comment by agarwal** [comment] 2016-11-07 14:10
I believe this was due to an empty Caml Hump feed. This feed is no longer updated, so I simply removed it in c28f4bac46f1fe41c4bd82a7dcb9ef9358510479.

Awaiting the build to update. We can close this issue once it is confirmed the problem got resolved.

**Comment by Chris00** [comment] 2016-11-07 15:11
On 2016-11-07, Ashish Agarwal wrote:

> I believe this was due to an empty Caml Hump feed. This feed is no 
> longer updated, so I simply removed it in c28f4ba.
> 
> Awaiting the build to update. We can close this issue once it is 
> confirmed the problem got resolved.

Sorry, I meant to tackle this but I do not succeed to find the time. 
Please leave it open until I — or somebody else :-) — commit a fix so 
that empty feeds do not cause problems.

**Comment by agarwal** [comment] 2016-11-07 17:14
@Chris00 The real problem is already open as #705. We can close this issue as it regards specifically the empty `planet/index.html` page, which is now working. I'll close, but reopen if you disagree.

**Closed as completed by agarwal** 2016-11-07 17:14 UTC
