### ISSUE TITLE
Planet is not updating

### ISSUE THREAD

**Issue by brabalan** [ocaml/v2.ocaml.org#897] opened 2017-05-30 06:20 UTC
The last entry aggregated at https://ocaml.org/community/planet/ is from May 11th. I know I've published two CWN since, and they do not show. Is there a problem with the aggregator?

**Comment by agarwal** [comment] 2017-05-30 14:37
The entire site is not being updated. Closing this as a duplicate of #898.

**Closed as completed by agarwal** 2017-05-30 14:37 UTC
