### ISSUE TITLE
Packages Page: Fix the layout on smaller screen sizes

### ISSUE THREAD

**Issue by mahakbansal2019** [ocaml/v2.ocaml.org#1350] opened 2021-04-01 06:43 UTC
On Smaller screen sizes the orientation of the two buttons doesn't look good.
"How to use opam" button should be shifted at the bottom of the first button on smaller screen sizes

![Screenshot from 2021-04-01 12-01-42](https://user-images.githubusercontent.com/53010252/113253787-6387ae80-92e3-11eb-84cc-71314ace574c.png)

@patricoferris What do you think about this ?

**Comment by patricoferris** [comment] 2021-04-01 07:11
Hi @mahakbansal2019, thank you for your patience. 

Unfortunately, this is a duplicate of #1259 I believe, so I'm going to close this issue. I know you've been waiting for an issue, I will try and get you one today.

**Closed as completed by patricoferris** 2021-04-01 07:11 UTC
