### ISSUE TITLE
Rearrange order of content in https://ocaml.org/meetings/

### ISSUE THREAD

**Issue by TildaDares** [ocaml/v2.ocaml.org#1416] opened 2021-04-05 13:20 UTC
The first heading in https://ocaml.org/meetings/ should be 'Ocaml Meetings' instead of 'Ocaml Users and Developers Workshop'. This arrangement adds structure to the page since the title of the page is 'Ocaml Meetings'.

<img width="769" alt="Screenshot 2021-04-05 at 14 18 41" src="https://user-images.githubusercontent.com/63427719/113577855-d792c100-9619-11eb-994c-690011e19044.png">

**Comment by pitag-ha** [comment] 2021-04-06 15:35
I do agree that if there's a section on a page with the same name as the title of the page, then that section should come first in general. Here the problem is that `OCaml Meetings` mostly includes pretty old meetings, whereas the `OCaml Users and Developers Workshop` section is up-to-date. So swapping the order would mean having the "out-of-date" section before the up-to-date section. Do you agree? Mybe renaming "OCaml Meetings" either to something more concrete or to "Other OCaml Meetings" might be an option?

**Comment by TildaDares** [comment] 2021-04-06 16:59
Or it could be 'Ocaml Past Meetings'. What do you think?

**Comment by pitag-ha** [comment] 2021-04-06 19:36
@TildaDares , this is a very simple issue. You have already worked on 2-3 or even more simple issues, haven't you? (see [this comment](https://github.com/ocaml/ocaml.org/issues/1245#issue-821019972) for reference of what I'm referring to:))

**Comment by patricoferris** [comment] 2021-04-07 10:13
I think the content is actually okay. `OCaml Users and Developers Workshop` (OUD) which is now just commonly known as the OCaml Workshop at ICFP is the main "meeting" for many OCaml devs. in the year. The OCaml Meetings is generally for anything else I think. Closing this for now, if anyone feels very strongly about this feel free to add your thoughts :))

**Closed as completed by patricoferris** 2021-04-07 10:13 UTC
